# train_esp.py — Runs on your LAPTOP
# Purpose: Trains CNN using data collected by collect_esp.py
#          Data matches EXACTLY how classify.py processes images on ESP32
#
# Author: Shravani Poman (with assistance from Claude AI)
# Course: AI for Engineers, Spring 2026

import os
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import random
import struct

DATA_DIR = "training_data_esp"
CLASSES = ["rock", "paper", "scissors"]
IMG_SIZE = 32
EPOCHS = 50
BATCH_SIZE = 16

def load_dataset():
    images = []
    labels = []
    for class_idx, cls in enumerate(CLASSES):
        folder = os.path.join(DATA_DIR, cls)
        if not os.path.exists(folder):
            continue
        files = [f for f in os.listdir(folder) if f.endswith('.npy')]
        print(f"Loading {cls}: {len(files)} images")
        for fname in files:
            pixels = np.load(os.path.join(folder, fname))
            if pixels.shape == (IMG_SIZE, IMG_SIZE):
                images.append(pixels)
                labels.append(class_idx)
    images = np.array(images).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
    labels = np.array(labels)
    print(f"\nTotal: {len(images)}")
    for i, cls in enumerate(CLASSES):
        print(f"  {cls}: {np.sum(labels == i)}")
    return images, labels

def augment(images, labels):
    aug_imgs = list(images)
    aug_lbls = list(labels)
    for img, lbl in zip(images, labels):
        aug_imgs.append(np.fliplr(img))
        aug_lbls.append(lbl)
        noisy = img + np.random.normal(0, 0.03, img.shape).astype(np.float32)
        aug_imgs.append(np.clip(noisy, 0, 1))
        aug_lbls.append(lbl)
        bright = img + np.random.uniform(-0.08, 0.08)
        aug_imgs.append(np.clip(bright, 0, 1).astype(np.float32))
        aug_lbls.append(lbl)
        shifted = np.roll(img, np.random.randint(-1, 2), axis=0)
        shifted = np.roll(shifted, np.random.randint(-1, 2), axis=1)
        aug_imgs.append(shifted)
        aug_lbls.append(lbl)
    return np.array(aug_imgs), np.array(aug_lbls)

def build_model():
    model = keras.Sequential([
        layers.Conv2D(12, (3, 3), activation='relu', padding='same',
                      input_shape=(IMG_SIZE, IMG_SIZE, 1)),
        layers.MaxPooling2D((2, 2)),
        layers.Conv2D(12, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D((2, 2)),
        layers.Conv2D(12, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D((2, 2)),
        layers.Flatten(),
        layers.Dropout(0.3),
        layers.Dense(24, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(3, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

def export_for_esp32(model):
    print("\n--- Exporting for ESP32 ---")
    conv_layers = [l for l in model.layers if 'conv2d' in l.name]
    dense_layers = [l for l in model.layers if 'dense' in l.name]

    with open("model_esp32.bin", "wb") as f:
        for i, layer in enumerate(conv_layers):
            k, b = layer.get_weights()
            print(f"  Conv{i}: {k.shape}, {b.shape} = {(k.size+b.size)*4} bytes")
            f.write(k.astype(np.float32).tobytes())
            f.write(b.astype(np.float32).tobytes())
        for i, layer in enumerate(dense_layers):
            w, b = layer.get_weights()
            print(f"  Dense{i}: {w.shape}, {b.shape} = {(w.size+b.size)*4} bytes")
            f.write(w.astype(np.float32).tobytes())
            f.write(b.astype(np.float32).tobytes())

    n_filters = [l.get_weights()[0].shape[3] for l in conv_layers]
    dense_shapes = [(l.get_weights()[0].shape, l.get_weights()[1].shape) for l in dense_layers]
    flatten_size = 4 * 4 * n_filters[-1]

    script = f'''# cnn_model.py — Auto-generated by train_esp.py
# CNN inference engine for ESP32 on-device classification
import struct
import math

CLASSES = ["rock", "paper", "scissors"]

def relu(x):
    return max(0.0, x)

def softmax(values):
    max_val = max(values)
    exp_vals = [math.exp(v - max_val) for v in values]
    total = sum(exp_vals)
    return [v / total for v in exp_vals]

class TinyCNN:
    def __init__(self):
        print("Loading CNN model...")
        self._load_weights()
        print("Model loaded!")
    
    def _load_weights(self):
        with open("model_esp32.bin", "rb") as f:
            data = f.read()
        offset = 0
        def read_floats(n):
            nonlocal offset
            vals = struct.unpack_from("<" + "f" * n, data, offset)
            offset += n * 4
            return list(vals)
        self.conv0_k = read_floats(3*3*1*{n_filters[0]})
        self.conv0_b = read_floats({n_filters[0]})
        self.conv1_k = read_floats(3*3*{n_filters[0]}*{n_filters[1]})
        self.conv1_b = read_floats({n_filters[1]})
        self.conv2_k = read_floats(3*3*{n_filters[1]}*{n_filters[2]})
        self.conv2_b = read_floats({n_filters[2]})
        self.dense0_w = read_floats({dense_shapes[0][0][0]}*{dense_shapes[0][0][1]})
        self.dense0_b = read_floats({dense_shapes[0][1][0]})
        self.dense1_w = read_floats({dense_shapes[1][0][0]}*{dense_shapes[1][0][1]})
        self.dense1_b = read_floats({dense_shapes[1][1][0]})

    def conv2d(self, inp, in_h, in_w, in_ch, kernel, bias, out_ch):
        out = [0.0] * (out_ch * in_h * in_w)
        for oc in range(out_ch):
            for y in range(in_h):
                for x in range(in_w):
                    val = bias[oc]
                    for ky in range(3):
                        for kx in range(3):
                            iy = y + ky - 1
                            ix = x + kx - 1
                            if 0 <= iy < in_h and 0 <= ix < in_w:
                                for ic in range(in_ch):
                                    k_idx = ((ky * 3 + kx) * in_ch + ic) * out_ch + oc
                                    p_idx = (iy * in_w + ix) * in_ch + ic
                                    val += inp[p_idx] * kernel[k_idx]
                    idx = (y * in_w + x) * out_ch + oc
                    out[idx] = relu(val)
        return out

    def maxpool2d(self, inp, in_h, in_w, channels):
        out_h = in_h // 2
        out_w = in_w // 2
        out = [0.0] * (out_h * out_w * channels)
        for y in range(out_h):
            for x in range(out_w):
                for c in range(channels):
                    max_val = -999999.0
                    for dy in range(2):
                        for dx in range(2):
                            iy = y * 2 + dy
                            ix = x * 2 + dx
                            idx = (iy * in_w + ix) * channels + c
                            if inp[idx] > max_val:
                                max_val = inp[idx]
                    out_idx = (y * out_w + x) * channels + c
                    out[out_idx] = max_val
        return out

    def dense(self, inp, weights, bias, in_size, out_size, use_relu=True):
        out = []
        for o in range(out_size):
            val = bias[o]
            for i in range(in_size):
                val += inp[i] * weights[i * out_size + o]
            if use_relu:
                val = relu(val)
            out.append(val)
        return out

    def predict(self, pixels):
        x = list(pixels)
        x = self.conv2d(x, 32, 32, 1, self.conv0_k, self.conv0_b, {n_filters[0]})
        x = self.maxpool2d(x, 32, 32, {n_filters[0]})
        x = self.conv2d(x, 16, 16, {n_filters[0]}, self.conv1_k, self.conv1_b, {n_filters[1]})
        x = self.maxpool2d(x, 16, 16, {n_filters[1]})
        x = self.conv2d(x, 8, 8, {n_filters[1]}, self.conv2_k, self.conv2_b, {n_filters[2]})
        x = self.maxpool2d(x, 8, 8, {n_filters[2]})
        x = self.dense(x, self.dense0_w, self.dense0_b, {flatten_size}, {dense_shapes[0][0][1]}, use_relu=True)
        x = self.dense(x, self.dense1_w, self.dense1_b, {dense_shapes[1][0][0]}, 3, use_relu=False)
        probs = softmax(x)
        best_idx = 0
        best_val = probs[0]
        for i in range(1, 3):
            if probs[i] > best_val:
                best_val = probs[i]
                best_idx = i
        return CLASSES[best_idx], best_val, probs
'''

    with open("cnn_model.py", "w") as f:
        f.write(script)
    print("  Saved cnn_model.py")
    model.save("rps_tiny_model.keras")
    print("  Saved rps_tiny_model.keras")

def main():
    print("=" * 50)
    print("  Training CNN for ESP32 on-device classification")
    print("=" * 50)

    images, labels = load_dataset()
    if len(images) == 0:
        print("No data! Run collect_esp.py first.")
        return

    print("\n--- Augmenting ---")
    images, labels = augment(images, labels)
    print(f"After augmentation: {len(images)}")

    indices = list(range(len(images)))
    random.shuffle(indices)
    images = images[indices]
    labels = labels[indices]

    split = int(len(images) * 0.8)
    train_imgs, test_imgs = images[:split], images[split:]
    train_lbls, test_lbls = labels[:split], labels[split:]

    model = build_model()
    model.summary()

    model.fit(train_imgs, train_lbls, epochs=EPOCHS, batch_size=BATCH_SIZE,
              validation_data=(test_imgs, test_lbls), verbose=1)

    loss, acc = model.evaluate(test_imgs, test_lbls, verbose=0)
    print(f"\nTest Accuracy: {acc * 100:.1f}%")

    preds = np.argmax(model.predict(test_imgs, verbose=0), axis=1)
    for i, cls in enumerate(CLASSES):
        mask = test_lbls == i
        if np.sum(mask) > 0:
            a = np.sum(preds[mask] == i) / np.sum(mask)
            print(f"  {cls}: {a * 100:.1f}%")

    export_for_esp32(model)
    print(f"\nDONE! Accuracy: {acc*100:.1f}%")
    print("\nUpload these to ESP32:")
    print("  - model_esp32.bin")
    print("  - cnn_model.py")

if __name__ == "__main__":
    main()
